### ISSUE TITLE
Presentation script: key findings

### ISSUE THREAD

**Issue by nicovandenhooff** [UBC-MDS/online-shoppers-purchasing-intention#12]
Script that presents the key useful findings of our EDA and ML analysis.  Also to include:

- [x] Format: Jupyter book **(Ari)**
- [x] Introduction - dataset **(Ari)**
- [x] Justification of our research question **(Ari)**
- [x] Discussion of EDA **(Ari)**
- [x] Discussion of data cleaning + feature engineering **(Tz)**
- [x] Present findings results (model selection + model tuning) **(Nico)**
- [x] Interpret findings and results **(Nico)**
- [x] Statement of future directions (what to change in next milestones) **(Nico)**
- [x] Total report 1-2 pages w/ figures **(All)**
- [x] At least 2-3 citations in a reference section (one can be data source) **(All)**
- [x] Programming language citations **(Tz)**

Other things to do:
- [x] Usage section (README) **(Ari)**
- [x] Dependencies function (README) **(Ari)**
- [x] Update project plan (README) **(Nico)**

**Comment by nicovandenhooff** [comment]
Hey guys @ytz @arijc76 I just updated the above based on what we discussed so that we can track what is left to do for milestone 2.  I checked off what we've already finished.  I put our names beside what we already assigned/finished.  Let me know if you have any ideas/preferences on how to split up the unassigned tasks.

**Comment by arijeetchatterjee** [comment]
Hi @nicovandenhooff @ytz I had added one citation for the data source in the jupyter book. Any suggestions on any other citations that we could use?
Also, I could add the Usage and Dependencies in the README if that's ok with everyone.

**Comment by nicovandenhooff** [comment]
@arijc76 that sounds good.  I was just reading the milestone which says:

> You are expected to have a reference section and cite 2-3 external sources (data source can be one of these citations) in addition to citing the programming languages and packages used. _Yes, you need to cite the programming languages and packages used in your project. You will learn how to do this in lecture._

I was thinking for a non-programming citation I could probably write something in our model section that draws from the original [Random Forest](https://link.springer.com/article/10.1023/A:1010933404324) paper and we could site that?  Open to other ideas as well.

I can update the project plan as well if that's okay.

**Comment by ytz** [comment]
Added [Tidy Data](https://www.jstatsoft.org/article/view/v059i10) paper in #27

**Comment by nicovandenhooff** [comment]
@ytz @arijc76 

Updated the above task list based on PR28.

Only things left to do are add programming citations, usage section, and dependencies section.

I may have some spare time tomorrow to update our EDA section in the Jupyter book with a bit of discussion as well if that is okay.

**Comment by ytz** [comment]
I'll do the programming language & packages citation

**Comment by arijeetchatterjee** [comment]
I'll add the usage and dependencies by tomorrow morning.

**Comment by nicovandenhooff** [comment]
All tasks completed.  Remaining missing items moved to separate issue.
