### ISSUE TITLE
Best performing model: Random forest vs. XGBoost

### ISSUE THREAD

**Issue by nicovandenhooff** [UBC-MDS/online-shoppers-purchasing-intention#22]
Hey @ytz @arijc76

Just cross validated the initial based models. 

It looks like RF and XGboost did the best (almost the exact same performance).  I think for the hyperparameter tuning script, I will focus on RF since this is consistent with the MDS curriculum, but let me know if you guys prefer otherwise.  I was thinking if we wanted to get fancy in the future (if we have time) we could add other models to the hyperparam script and then ensemble them together to see if that gave us better performance.

Cheers,
Nico

**Comment by arijeetchatterjee** [comment]
Sounds good @nicovandenhooff

**Comment by ytz** [comment]
I'm ok with that. Thanks @nicovandenhooff

**Comment by nicovandenhooff** [comment]
Resolved.  RF to be main model.
