### ISSUE TITLE
Jupyter book: Publish

### ISSUE THREAD

**Issue by nicovandenhooff** [UBC-MDS/online-shoppers-purchasing-intention#29]
I think we may want to publish our Jupyter book online once it is finalized for milestone 2.

Opening an issue as a reminder for us.

Instructions here: https://jupyterbook.org/start/publish.html

**Comment by ytz** [comment]
Perhaps either @nicovandenhooff or @arijc76 can submit to Canvas this week? As submitter you can also:
- Publish Jupyter book
- Check whether we missed out anything
- Release 0.02

**Comment by nicovandenhooff** [comment]
Sure @ytz  - I don't mind submitting this week, and then @arijc76 can submit next week if that works?
