### ISSUE TITLE
Milestone 2: Missing items

### ISSUE THREAD

**Issue by nicovandenhooff** [UBC-MDS/online-shoppers-purchasing-intention#32]
Hi guys @ytz @arijc76

I just checked our work to date against the [milestone 2 requirements](https://pages.github.ubc.ca/mds-2021-22/DSCI_522_dsci-workflows_students/materials/assignments/milestone2.html).  I think we are potentially missing 2 items for the Milestone 2 requirements - see below:

### Missing item 1: Function tests

Details: Milestone 2 states: _All functions written for the project scripts should have sensible tests._ This is also confirmed by tiff in this [slack post](https://ubc-mds.slack.com/archives/C24HUNRJL/p1637900187315800) 

Solution: I'm thinking we can just add some simple tests with fake data to each of the scripts that were assigned to us this week, inside of the same scripts we wrote, then in the future we can merge these into a test document.  I guess @ytz and I drew the short straw here because of how many functions we wrote :(

### Missing item 2: EDA needs some discussion in the report

Details:  Milestone 2 states: _Your question, analysis and visualization should make sense. It doesn’t have to be complicated, but you should tell a story and have a narrative. Specifically, this should come through in your README and **final report file**._

Solution: I think this is easy, we just need to add a couple sentences to the `.md` file for the EDA part of our jupyter book, describing what each visualization shows.  I think we actually had this in our original EDA `.ipynb` file, so we may just be able to copy/paste this.

Let me know what you think on the above.  Thanks.

**Comment by ytz** [comment]
I'm ok with your suggestions. I'll try to add some test functions now.

**Comment by arijeetchatterjee** [comment]
I'm ok with the suggestions as well. I'll make the changes in the data analysis md file and the eda chart generation script.

**Comment by nicovandenhooff** [comment]
Sounds good - I actually added very simple tests to my scripts just testing return types.

I'll do a final check of the project tomorrow morning, publish the JL book, and create the release and submit by tomorrow noon.
