### ISSUE TITLE
Improve doc on model comparison

### ISSUE THREAD

**Issue by ytz** [UBC-MDS/online-shoppers-purchasing-intention#43]
> How you would like to evaluate your models and compare them together. What are your metrics? Accuracy, interpretability or...

as seen in #41

**Comment by nicovandenhooff** [comment]
@arijc76 @ytz 

If I have time this week, I may also try adding precision-recall curves to the ML section if you guys are okay with that.

**Comment by nicovandenhooff** [comment]
@ytz @arijc76 

Just a general FYI, will have the updated ML analysis pushed to the repo later tonight.  I've reformatted the confusion matrices so that they are side by side (looks way nicer) and also am currently adding precision recall curves.

**Comment by nicovandenhooff** [comment]
Addressed.  PR curves added and discussion updated.
