### ISSUE TITLE
MakeFile

### ISSUE THREAD

**Issue by ytz** [UBC-MDS/online-shoppers-purchasing-intention#44]
- [x] Create MakeFile
- [x] Update README with Make instructions
- [x] Automate Jupyter Book with Make

**Comment by nicovandenhooff** [comment]
This [post](https://askubuntu.com/questions/86822/how-can-i-copy-the-contents-of-a-folder-to-another-folder-in-a-different-directo)  may help automate the copy/pasting of the JB files to the doc folder.

**Comment by arijeetchatterjee** [comment]
Thanks Nico. That post helped in the copying/pasting of the files.
