### ISSUE TITLE
Move tests into separate .py file

### ISSUE THREAD

**Issue by nicovandenhooff** [UBC-MDS/online-shoppers-purchasing-intention#50]
Just a reminder for us to move our test functions into a separate `.py` file.  

I'm happy to do this for us as I also have a few updates to make the ML scripts this week (will be done by tomorrow night), but let me know if anyone prefers another approach

**Comment by ytz** [comment]
Yea that works for me.

**Comment by arijeetchatterjee** [comment]
Thanks. Works for me too.
