### ISSUE TITLE
PR curve to use probability

### ISSUE THREAD

**Issue by ytz** [UBC-MDS/online-shoppers-purchasing-intention#62]
@nicovandenhooff @arijc76 I notice our PR curve only has 1 cut-off point. I think it will be more useful (and accurate) to plot a PR curve with multiple thresholds. We can do this by outputting probability instead of labels in `cross_val_predict`. I tried making some changes to the code, and it will look something like this:
![model_pr_curves](https://user-images.githubusercontent.com/1884616/144700244-60591dd4-c9c2-458e-8d75-1bca58648f04.png)

What do you guys think? Let me know if you want me to elaborate.

**Comment by nicovandenhooff** [comment]
Looks much better!  Feel free to change the code to your version.  I couldn’t figure out how to get the plot to have multiple thresholds so looking forward to seeing your code as well.
