### ISSUE TITLE
Docker issues

### ISSUE THREAD

**Issue by ytz** [UBC-MDS/online-shoppers-purchasing-intention#73]
Currently there is an issue running this repo in docker on M1 macbook. Script will be stuck at `src/model_selection.py`, before outputting to terminal after 40 minutes

**Update1**: 
Tried `docker build` locally with `--platform linux/amd64`. Same problem.

**Update2**: 
Using nico's new MakeFile now. Initially I encountered a problem with Altair in `eda_charts.py`, but was resolved when I update Docker Desktop. Also, I commented out the warning in `model_selection.py`, and the script printed out this:
```
python src/model_selection.py --data_path=data/processed/ --output_path=results/model_selection/
/opt/conda/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
```
This suggest that the script is indeed running, just very slowly.

**Update3:**
Adding `print` statements in `get_mean_cv_scores` forces it to print previous console output to console. Bottleneck seems to be at training, start from `LogisticRegression`

**Comment by ytz** [comment]
Tried `docker build` locally with `--platform linux/amd64`. Same problem.

**Comment by arijeetchatterjee** [comment]
I am not able to run the docker due to the below error, which, after searching online, looks like a known M1 docker issue as well.
```
#
# Fatal process OOM in Failed to reserve virtual memory for CodeRange
#
```

**Comment by ytz** [comment]
@arijc76, I was able to bypass this error by either:

1. Increasing memory in Docker Desktop [here](https://ubc-mds.slack.com/archives/C24HUNRJL/p1639036437139000)
2. Upgrading Docker Desktop

However, I'm thinking we shouldn't spend too much time on this M1 issue. @nicovandenhooff , is it alright if you handle the final submission, since you can run it on docker and do the final check/release?

**Comment by nicovandenhooff** [comment]
@ytz  yup - no problem, I can also add the final summary/abstract to our report before the submission.  And sounds good yeah let's just leave the M1 issue for now
