### ISSUE TITLE
Milestone 2 Review

### ISSUE THREAD

**Issue by mohamad-amin** [UBC-MDS/online-shoppers-purchasing-intention#76]
I'm impressed by your beautiful scripts! Thanks.

The only improvements that could possibly still be there:
* Outlier detection could be better
* You could have more explanations for your EDA plots

I honestly can't think of many things that could be better in the context of this Milestone. Great job!

**Comment by nicovandenhooff** [comment]
@ytz @arijc76 What do you guys think about this feedback?  I think we have fixed the EDA already.  For outliers I think we have increased discussion on EDA as well.  I think we are probably okay to just leave everything as is but let me know if you think otherwise

**Comment by arijeetchatterjee** [comment]
Yes, I think we can leave everything as is since we covered the EDA in more detail subsequently.

**Comment by nicovandenhooff** [comment]
Thanks for the feedback!   We have addressed this in our final report.
